name: Jan Kaiponen
favicon: null
layout_spectrum: 0.023399795638397336
typography_spectrum: 0.5463445365894586
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.2945609078742564
  lightness: 0.5679907533340156
  saturation: 0.742393187712878
  rhythmicContrast: 0.7752646594308317
purpose: []
